# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-014bb31d-44d6-49cc-952f-69beb5a52b60";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-014bb31d-44d6-49cc-952f-69beb5a52b60".device = "/dev/disk/by-uuid/014bb31d-44d6-49cc-952f-69beb5a52b60";
  boot.initrd.luks.devices."luks-47c75a2c-53a6-4573-9641-0967577ecb46".device = "/dev/disk/by-uuid/47c75a2c-53a6-4573-9641-0967577ecb46";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/289A-A784";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-47c75a2c-53a6-4573-9641-0967577ecb46"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
