# mise - polyglot runtime manager module for NixOS
#
# This module provides comprehensive mise support on NixOS, including:
# - mise package installation
# - nix-ld configuration for dynamically linked binaries
# - FHS compatibility symlinks for native gem/extension builds
# - Extra packages for specific tools (e.g., lolcommits)
#
# Usage:
#   programs.mise.enable = true;
#
# The FHS compatibility feature creates symlinks in /usr/bin for common tools
# (mkdir, install, rm, cp) that are hardcoded in Makefiles generated by
# Ruby's extconf.rb and other build systems.

{ config, lib, pkgs, ... }:

let
  cfg = config.programs.mise;
in
{
  options.programs.mise = {
    enable = lib.mkEnableOption "mise - polyglot runtime manager";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.mise;
      defaultText = lib.literalExpression "pkgs.mise";
      description = "The mise package to install.";
    };

    enableFhsCompat = lib.mkOption {
      type = lib.types.bool;
      default = !config.services.envfs.enable;
      description = ''
        Create FHS-compatible symlinks in /usr/bin for common tools.
        Required for building native Ruby gems that hardcode paths like /usr/bin/mkdir.

        This is needed because Ruby's extconf.rb generates Makefiles with hardcoded
        /usr/bin paths, which don't exist on NixOS by default.

        Automatically disabled when services.envfs.enable is true, as envfs provides
        /usr/bin access via a read-only mount.
      '';
    };

    nixLdLibraries = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = with pkgs; [
        # Common libraries needed by mise-installed language runtimes
        zlib
        openssl
        readline
        libyaml
        libffi
        gmp
        ncurses
        stdenv.cc.cc.lib
        # For gems with native extensions (e.g., rmagick)
        imagemagick
      ];
      description = "Libraries to include in nix-ld for mise-installed tools.";
    };

    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = with pkgs; [
        # lolcommits dependencies
        imagemagick      # Image manipulation (runtime)
        imagemagick.dev  # ImageMagick headers and pkg-config for native gem builds
        ffmpeg           # Webcam capture
        mplayer          # Alternative webcam capture
        v4l-utils        # Video4Linux utilities
      ];
      description = ''
        Extra packages needed by mise-installed tools at runtime.
        Default includes lolcommits dependencies.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Install mise and extra packages
    environment.systemPackages = [ cfg.package ] ++ cfg.extraPackages;

    # nix-ld setup for mise-installed binaries
    # This allows dynamically linked binaries from mise to find shared libraries
    programs.nix-ld.enable = true;
    programs.nix-ld.libraries = cfg.nixLdLibraries;

    # Expose pkg-config paths for native gem compilation (e.g., rmagick)
    environment.variables.PKG_CONFIG_PATH = lib.mkDefault
      "${pkgs.imagemagick.dev}/lib/pkgconfig";

    # FHS compatibility symlinks for native gem builds
    # Ruby's extconf.rb generates Makefiles that hardcode /usr/bin paths
    # Without these symlinks, `make install` fails with errors like:
    #   /bin/sh: line 1: /usr/bin/mkdir: No such file or directory
    system.activationScripts.fhsCompat = lib.mkIf cfg.enableFhsCompat {
      text = ''
        mkdir -p /usr/bin
        ln -sf ${pkgs.coreutils}/bin/mkdir /usr/bin/mkdir
        ln -sf ${pkgs.coreutils}/bin/install /usr/bin/install
        ln -sf ${pkgs.coreutils}/bin/rm /usr/bin/rm
        ln -sf ${pkgs.coreutils}/bin/cp /usr/bin/cp
      '';
    };
  };
}
