---
# Enterprise playbook for Microsoft Intune and Defender ATP
# Run this separately after the main setup is complete

- name: Microsoft Intune and Defender ATP Installation
  hosts: localhost
  connection: local
  become: no

  pre_tasks:
    - name: Display enterprise setup information
      debug:
        msg: |
          ========================================
          Microsoft Enterprise Tools Installation
          ========================================

          This playbook will install:
          1. Microsoft Intune Portal
          2. Microsoft Defender for Endpoint (mdatp)

          Requirements:
          - Ubuntu 22.04 or 24.04 LTS
          - Internet connectivity to packages.microsoft.com
          - For mdatp: WindowsDefenderATPOnboardingPackage.zip

          IMPORTANT:
          - Both tools require a system reboot after installation
          - Your device will be enrolled as a corporate-owned device
          - Before Ubuntu OS upgrades, uninstall mdatp first

          ========================================

    - name: Confirm installation
      pause:
        prompt: |

          Press ENTER to continue with installation, or Ctrl+C to cancel.

  roles:
    - role: intune
      tags: ['intune']

    - role: mdatp
      tags: ['mdatp']

  post_tasks:
    - name: Display completion message
      debug:
        msg: |
          ========================================
          Enterprise Tools Installation Complete
          ========================================

          IMPORTANT: Reboot your system now!
            sudo reboot

          After reboot:

          1. Microsoft Intune:
             - Launch the Intune Portal application
             - Sign in with your organization credentials
             - Complete the enrollment process

          2. Microsoft Defender ATP:
             - Verify health: sudo mdatp health
             - Test connectivity: sudo mdatp connectivity test
             - Check status: sudo mdatp health --field all

          Troubleshooting:

          - Reset Intune: sudo /usr/local/bin/reset-intune.sh
          - Check mdatp logs: sudo journalctl -u mdatp

          Management:

          - Uninstall Intune: sudo apt remove intune-portal
          - Purge Intune data: sudo apt purge intune-portal
          - Uninstall mdatp: Download mde_installer.sh and run with --remove

          ========================================

    - name: Suggest reboot
      debug:
        msg: "REBOOT REQUIRED: Please reboot your system to complete the installation."
