---
# Main playbook for Ubuntu 24.04 LTS system setup
# This playbook configures the desktop environment and development tools

- name: Ubuntu 24.04 LTS Desktop and Development Setup
  hosts: localhost
  connection: local
  become: no

  pre_tasks:
    - name: Display setup information
      debug:
        msg: |
          Starting Ubuntu 24.04 LTS system setup...
          This will install and configure:
          - Base system packages and locale settings
          - Hyprland desktop environment
          - Desktop applications (browsers, office, media)
          - Japanese input method (fcitx5 with CSKK)
          - Development tools (Go, Python, Node.js, Rust, Docker)
          - Fonts (Noto, Cica, JetBrains Mono Nerd Font)
          - Security tools (1Password, GNOME Keyring)

    - name: Check if running on Ubuntu
      fail:
        msg: "This playbook is designed for Ubuntu. Detected OS: {{ ansible_distribution }}"
      when: ansible_distribution != "Ubuntu"

  roles:
    - role: base
      tags: ['base', 'system']

    - role: hyprland
      tags: ['hyprland', 'desktop']

    - role: apps
      tags: ['apps', 'desktop']

    - role: japanese
      tags: ['japanese', 'input']

    - role: development
      tags: ['development', 'dev']

    - role: fonts
      tags: ['fonts']

    - role: security
      tags: ['security']

  post_tasks:
    - name: Display completion message
      debug:
        msg: |
          ========================================
          Setup Complete!
          ========================================

          Next steps:

          1. REBOOT your system (recommended)
             sudo reboot

          2. After reboot, log in using the ly display manager
             Select Hyprland as your session

          3. Configure user environment:
             - Run: chezmoi init
             - Run: mise install

          4. Configure fcitx5:
             - Run: fcitx5-configtool
             - Add CSKK input method
             - Set keyboard shortcut to switch input methods

          5. Optional: Install Microsoft Intune and Defender ATP
             Download WindowsDefenderATPOnboardingPackage.zip from Microsoft
             Then run:
             ansible-playbook enterprise.yml --ask-become-pass \
               --extra-vars "mdatp_onboarding=/path/to/WindowsDefenderATPOnboardingPackage.zip"

          6. Some tools may need to be installed via user package managers:
             - Use mise for language version management
             - Use cargo for Rust tools
             - Use go install for Go tools

          ========================================

    - name: Suggest reboot
      debug:
        msg: "A system reboot is recommended to apply all changes."
