# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-49d4f27a-ac37-4083-9648-7073d5171762";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-49d4f27a-ac37-4083-9648-7073d5171762".device = "/dev/disk/by-uuid/49d4f27a-ac37-4083-9648-7073d5171762";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D85E-CED5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
