#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export EDITOR=vim

command -v mise &>/dev/null && eval "$(mise activate bash)"
command -v atuin &>/dev/null && eval "$(atuin init --disable-up-arrow bash)"

[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh

