# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-459af733-88f0-403d-a984-2861fbbb8e0e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-459af733-88f0-403d-a984-2861fbbb8e0e".device = "/dev/disk/by-uuid/459af733-88f0-403d-a984-2861fbbb8e0e";
  boot.initrd.luks.devices."luks-956cd899-5f33-4af3-b2e0-368d6bfa64ba".device = "/dev/disk/by-uuid/956cd899-5f33-4af3-b2e0-368d6bfa64ba";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F9BD-13E5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-956cd899-5f33-4af3-b2e0-368d6bfa64ba"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
