# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-55a6e6f8-93b2-42eb-970b-f6b70d2fd40a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-55a6e6f8-93b2-42eb-970b-f6b70d2fd40a".device = "/dev/disk/by-uuid/55a6e6f8-93b2-42eb-970b-f6b70d2fd40a";
  boot.initrd.luks.devices."luks-b702fd31-da20-4a22-841a-0e3c69a7ccc4".device = "/dev/disk/by-uuid/b702fd31-da20-4a22-841a-0e3c69a7ccc4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/585D-EA80";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b702fd31-da20-4a22-841a-0e3c69a7ccc4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
