keys:
  - &wk2511058 age1m4uv4je7y7k9zfh7dmlu034jfan44n9yjfesv48qaj58l60aku5qggr6jq
  - &junior age1ywrnya3a0jduxy7lrfv0vd0g37e8996hnm6afzv3q3n20tplrgcs50tum8

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *wk2511058
          - *junior
